language: scala

jdk:
   - oraclejdk8
   - oraclejdk11
   - openjdk11

scala:
   - 2.11.12
   - 2.12.6
script:
   - sbt ++$TRAVIS_SCALA_VERSION clean
   - sbt ++$TRAVIS_SCALA_VERSION coverage test -J-Xss4M
after_success:
   - sbt coverageReport coveralls
