language: scala

jdk:
   - oraclejdk8
   - openjdk11
   - openjdk12
   - openjdk13

scala:
   - 2.11.12
   - 2.12.8
script:
   - sbt ++$TRAVIS_SCALA_VERSION clean
   - sbt ++$TRAVIS_SCALA_VERSION coverage test -J-Xss4M
after_success:
   - sbt coverageReport coveralls
