package com.axtstar.asta4e.test_class

case class Data_VIRTICAL(A1:String,
                           A2:String,
                           A3:String,
                           A4:String,
                           A5:String,
                           A6:String,
                           A7:String,
                           A8:String,
                           A9:String,
                           A10:String,
                           A11:String,
                           A12:String,
                           A13:String,
                           A14:String,
                           A15:String,
                           A16:String,
                           A17:String,
                           A18:String,
                           A19:String,
                           A20:String,
                           A21:String,
                           A22:String,
                           A23:String,
                           A24:String,
                           A25:String,
                           A26:String,
                           A27:String,
                           A28:String,
                           A29:String,
                           A30:String,
                           A31:String,
                           A32:String,
                           A33:String
               )
