package com.axtstar.asta4e.test_class

case class Data_HOLIZONTAL(A1:String,
                B1:String,
                C1:String,
                D1:String,
                E1:String,
                F1:String,
                G1:String,
                H1:String,
                I1:String,
                J1:String,
                K1:String,
                L1:String,
                M1:String,
                N1:String,
                O1:String,
                P1:String,
                Q1:String,
                R1:String,
                S1:String,
                T1:String,
                U1:String,
                V1:String,
                W1:String,
                X1:String,
                Y1:String,
                Z1:String,
                AA1:String,
                AB1:String,
                AC1:String,
                AD1:String,
                AE1:String,
                AF1:String,
                AG1:String
               )
