name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests default 2.12.13
      run: sbt test
    - name: Run tests 2.11.12
      run: sbt ++2.11.12 test
    - name: Run tests 2.13.3
      run: sbt ++2.13.3 test
